use crate::ai::GuidedFollowUpKind;
use crate::app::{AiLaunchIntent, AiPreflightState, LiveSnapshot, Screen};

#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Tick,
    Quit,
    NextScreen,
    PreviousScreen,
    ShowScreen(Screen),
    RefreshRequested,
    RefreshStarted {
        families: Vec<String>,
        manual: bool,
    },
    LiveSnapshotLoaded {
        snapshot: Box<LiveSnapshot>,
        summary: String,
    },
    RefreshFailed {
        message: String,
    },
    PreviousDay,
    NextDay,
    PreviousTimelinePoint,
    NextTimelinePoint,
    PreviousEvent,
    NextEvent,
    TimelineZoomIn,
    TimelineZoomOut,
    ToggleWorkoutFilter,
    ToggleTagFilter,
    ToggleSessionFilter,
    PreviousTrendWindow,
    NextTrendWindow,
    CyclePatternMetric,
    CycleReviewMode,
    CycleReviewFocus,
    PreviousReviewCard,
    NextReviewCard,
    RequestAiLaunch(AiLaunchIntent),
    AiPreflightPrepared {
        preflight: Box<AiPreflightState>,
        status_line: String,
    },
    AiPreflightFailed {
        message: String,
    },
    DismissAiPreflight,
    CycleAiPreflightPrivacyProfile,
    ConfirmAiPreflight,
    RequestCancelAiRun,
    RequestAiGuidedFollowUp(GuidedFollowUpKind),
    RequestAiRerunNextPrivacy,
    RequestAiRerunNextModel,
    RequestAiComparePreviousSnapshot,
    RequestAiGenerateReport,
    RequestJumpToAiEvidence,
    JumpToDayAndScreen {
        day: String,
        screen: Screen,
        status_line: String,
    },
    PreviousAiBrowserTab,
    NextAiBrowserTab,
    PreviousAiBrowserItem,
    NextAiBrowserItem,
}
