use crate::ai::GuidedFollowUpKind;
use crate::app::{AiBrowserTab, AiLaunchIntent, AiPreflightState, LiveSnapshot, Screen};
use crate::navigation::NavMove;

#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Tick,
    Quit,
    FocusNextRegion,
    FocusPreviousRegion,
    MoveFocusedRegion(NavMove),
    MoveTransientFocus(NavMove),
    ActivateFocusedRegion,
    Back,
    ToggleHelp,
    OpenSearch,
    CloseSearch,
    SearchAppend(char),
    SearchBackspace,
    SearchNextResult,
    SearchPreviousResult,
    ShowScreen(Screen),
    RefreshRequested,
    RefreshStarted {
        families: Vec<String>,
        manual: bool,
    },
    LiveSnapshotLoaded {
        snapshot: Box<LiveSnapshot>,
        summary: String,
    },
    RefreshFailed {
        message: String,
    },
    StatusMessage {
        message: String,
    },
    PreviousDay,
    NextDay,
    PreviousTimelinePoint,
    NextTimelinePoint,
    PreviousEvent,
    NextEvent,
    TimelineZoomIn,
    TimelineZoomOut,
    ToggleWorkoutFilter,
    ToggleTagFilter,
    ToggleSessionFilter,
    PreviousTrendWindow,
    NextTrendWindow,
    CyclePatternMetric,
    PreviousReviewCard,
    NextReviewCard,
    RequestAiLaunch(AiLaunchIntent),
    AiPreflightPrepared {
        preflight: Box<AiPreflightState>,
        status_line: String,
    },
    AiPreflightFailed {
        message: String,
    },
    DismissAiPreflight,
    CycleAiPreflightPrivacyProfile,
    ConfirmAiPreflight,
    RequestCancelAiRun,
    RequestAiGuidedFollowUp(GuidedFollowUpKind),
    RequestAiRerunNextPrivacy,
    RequestAiRerunNextModel,
    RequestAiComparePreviousSnapshot,
    RequestAiGenerateReport,
    RequestJumpToAiEvidence,
    JumpToDayAndScreen {
        day: String,
        screen: Screen,
        status_line: String,
    },
    JumpToAiBrowserRecord {
        tab: AiBrowserTab,
        record_id: String,
        status_line: String,
    },
    PreviousAiBrowserItem,
    NextAiBrowserItem,
}
